name: bimsina_clock
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper

  flutter_svg: ^0.14.4
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.7.1
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/IndieFlower-Regular.ttf
    - family: Crystal
      fonts:
        - asset: assets/Crystal.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
